#!/usr/bin/env python3
# boj.kr/1913
N = int(input())
grid = [[0] * N for _ in range(N)]

def rotate_matrix(x, y):
    dx, dy = 0, 1
    new_x, new_y = x+dx, y+dy
    if 1<new_x<=N and 1<new_y<=N and grid[new_x][new_y]==0: #TODO:범위 맞는지 다시 한 번 체크
        x, y = new_x, new_y
    else:
        dx, dy = -dy, dx
        x, y = x+dx, y+dy
    return grid

for i in range(1, N):
    x, y = N//2, N//2
    grid[x][y] = i
    print(f'앞으로 {i}칸 전진합니다.')
    print('우회전 하세요') # TODO: rotate_matrix()
    print(f'앞으로 {i}칸 전진합니다.')
    print('우회전 하세요') # rotate_matrix()
    print('보폭 늘리세요')
print(f'앞으로 {N-1}칸 전진합니다.')

